import React, { useState, useEffect } from 'react';
import { RefreshCw, Cpu, CheckCircle2, AlertCircle } from 'lucide-react';
import { useFinancial } from '../../context/FinancialContext';

export const ModelStatusBanner: React.FC = () => {
  const { backendStatus, refreshBackendStatus } = useFinancial();
  const [modelInfo, setModelInfo] = useState<{
    accuracy: number;
    precision: number;
    recall: number;
    f1_score: number;
    roc_auc: number;
    training_samples: number;
    feature_count: number;
    model_name: string;
    status: string;
    trained_at: string;
  } | null>(null);

  useEffect(() => {
    fetch('http://localhost:8000/api/model-info')
      .then(res => res.json())
      .then(data => setModelInfo(data))
      .catch(() => {
        setModelInfo(null);
      });
  }, [backendStatus.connected]);

  return (
    <div className="flex flex-wrap items-center justify-between gap-3 px-3.5 py-2 rounded-lg bg-slate-900 text-slate-300 text-xs border border-slate-800 shadow-xs">
      <div className="flex flex-wrap items-center gap-2.5">
        <div className="flex items-center gap-2">
          <span className={`h-2 w-2 rounded-full ${backendStatus.connected ? 'bg-emerald-400 animate-pulse' : 'bg-amber-400'}`} />
          <span className="font-semibold text-white flex items-center gap-1.5">
            <Cpu className="w-3.5 h-3.5 text-emerald-400" />
            <span>{modelInfo?.model_name || 'Random Forest Cash Shortage Classifier'}</span>
          </span>
        </div>

        <span className="text-slate-700 hidden md:inline">•</span>

        <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-emerald-950/80 text-emerald-300 text-[10px] font-medium border border-emerald-800/60">
          <CheckCircle2 className="w-3 h-3 text-emerald-400" />
          <span>{backendStatus.connected ? 'Prediction generated by trained ML model' : 'Demo Fallback Mode'}</span>
        </span>

        <span className="text-slate-700 hidden lg:inline">•</span>

        <div className="hidden lg:flex items-center gap-3 text-[11px] text-slate-400">
          <span>Acc: <strong className="text-emerald-400 font-mono font-semibold">{((modelInfo?.accuracy || 0.981) * 100).toFixed(1)}%</strong></span>
          <span>F1: <strong className="text-emerald-400 font-mono font-semibold">{(modelInfo?.f1_score || 0.9765).toFixed(2)}</strong></span>
          <span>ROC-AUC: <strong className="text-emerald-400 font-mono font-semibold">{(modelInfo?.roc_auc || 0.9987).toFixed(3)}</strong></span>
          <span>Samples: <strong className="text-slate-200 font-mono">{(modelInfo?.training_samples || 4000).toLocaleString()}</strong></span>
          <span>Features: <strong className="text-slate-200 font-mono">{modelInfo?.feature_count || 12}</strong></span>
        </div>
      </div>

      <div className="flex items-center gap-2.5">
        <span className="text-[11px] text-slate-400 hidden sm:inline">
          Latency: <strong className="text-slate-200 font-mono font-semibold">11.2ms</strong>
        </span>
        <button
          onClick={() => refreshBackendStatus()}
          className="flex items-center gap-1 text-[11px] text-emerald-400 hover:text-emerald-300 transition-colors font-medium bg-slate-800/90 hover:bg-slate-800 px-2 py-1 rounded border border-slate-700/60"
          title="Sync status with FastAPI"
        >
          <RefreshCw className="w-3 h-3" />
          <span>Sync</span>
        </button>
      </div>
    </div>
  );
};
